// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynUWKp4Hq8gn8p3DpssHwLUGpqDckLRs',
    appId: '1:786652033046:web:e388cce79e9fe04ac48537',
    messagingSenderId: '786652033046',
    projectId: 'efficient-rides-project',
    authDomain: 'efficient-rides-project.firebaseapp.com',
    storageBucket: 'efficient-rides-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XB2Fqgdei1_SUH8El2Hvn5ftvq2A5uQ',
    appId: '1:786652033046:android:c4641361f32f1ed3c48537',
    messagingSenderId: '786652033046',
    projectId: 'efficient-rides-project',
    storageBucket: 'efficient-rides-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPYUnqF53CSduiEr0FR7E7Gspw9P6Kg0',
    appId: '1:786652033046:ios:cfc7f86e301a5b0dc48537',
    messagingSenderId: '786652033046',
    projectId: 'efficient-rides-project',
    storageBucket: 'efficient-rides-project.appspot.com',
    iosClientId:
        '786652033046-eok69d7autcfijpdv343ib990nineeie.apps.googleusercontent.com',
    iosBundleId: 'com.snapsid.loginuicolors',
  );
}
